// swift-tools-version: 5.8

// Do not edit this file, this is here so it does not show in Xcode.
import PackageDescription

let package = Package(
  name: "todos-app",
  platforms: [
  ],
  products: [
  ],
  dependencies: [
  ],
  targets: [
  ]
)
